force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Employee Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill__c/Skill__c.object-meta.xml
<CustomObject>
    <label>Skill</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Skill ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skills</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skill__c/fields/Employee_Id__c.field-meta.xml
<CustomField>
    <fullName>Employee_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee Id</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Skills</relationshipLabel>
    <relationshipName>Skills</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Skill__c/fields/Skill_Name__c.field-meta.xml
<CustomField>
    <fullName>Skill_Name__c</fullName>
    <label>Skill Name</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetSkill.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 10-12-2021
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class GetSkill {
    @AuraEnabled(cacheable=true)
    public static List<Skill__c> getSkills(String empId) {
        List<Employee__c> lstId = [SELECT Id FROM Employee__c WHERE Name = :empId LIMIT 1];
        ID rowId = lstId[0].id;
        return [SELECT Skill_Name__c FROM Skill__c WHERE Employee_Id__c = :rowId];
    }

    /*@AuraEnabled(cacheable=true)
    public static List<Skill__c> getSkillss(String empId) {
        return [SELECT Skill_Name__c FROM Skill__c WHERE Employee_Id__c = :empId];
    }*/

    @AuraEnabled
    public Static Boolean submitt(String comment, String name){
        Employee__c emp = [SELECT Comments__c FROM Employee__c WHERE Name=:name LIMIT 1];
        emp.Comments__c = comment;
        try{
            update emp;
            return true;
        }
        catch (Exception e) {
            System.debug(e.getMessage());
        }
        return false;
     }
    
    
}